server:
  address: 0.0.0.0
  port: 8089
  servlet:
    context-path: /gastos-mensais

spring:
  application:
    name: gastos-mensais
  data:
    mongodb:
      uri: mongodb://localhost:27017/gastos-mensais
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data: DEBUG


