server:
  address: 0.0.0.0
  port: 8089
  servlet:
    context-path: /gastos-mensais

spring:
  application:
    name: gastos-mensais
  data:
    mongodb:
      uri: mongodb+srv://admin:LuizJoao123@cluster.y2vw5.mongodb.net/
      data-base: testandoMensal

  jackson:
    time-zone: UTC
    serialization:
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: minha-chave-super-secreta-e-segura-minha-chave-super-secreta-e-segura
  expiration: 86400000

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data: DEBUG


